"Libro 1": [
  "1. Habilidades del Putt (Anotar número de putts metidos)",
  "10 putts caída der→izq 3 pies",
  "10 putts caída izq→der 3 pies",
  "10 putts rectos 3 pies",
  "",
  "10 putts caída der→izq 6 pies",
  "10 putts caída izq→der 6 pies",
  "10 putts rectos 6 pies",
  "",
  "10 putts caída der→izq 9 pies",
  "10 putts caída izq→der 9 pies",
  "10 putts rectos 9 pies",
  "",
  "10 putts caída der→izq 12 pies",
  "10 putts caída izq→der 12 pies",
  "10 putts rectos 12 pies",
  "",
  "10 putts caída der→izq 15 pies",
  "10 putts caída izq→der 15 pies",
  "10 putts rectos 15 pies",
  "",
  "2. Prueba de Putt de Acercamiento (Anota cuántos quedan a 3 pies del hoyo)",
  "25 putts desde 20 pies",
  "25 putts desde 30 pies",
  "25 putts desde 40 pies",
  "25 putts desde 50 pies",
  "",
  "3. Chipping desde el Fringe (Anota el número de chips a cada distancia)",
  "50 chips a bandera roja (corta), a una distancia de 3 pies",
  "50 chips a bandera amarilla (media), a una distancia de 4 pies",
  "50 chips a bandera azul (larga), a una distancia de 5 pies",
  "",
  "4. Chipping desde el Rough (Anota el número de chips a cada distancia)",
  "50 chips a bandera roja (corta), a una distancia de 3 pies",
  "50 chips a bandera amarilla (media), a una distancia de 4 pies",
  "50 chips a bandera azul (larga), a una distancia de 5 pies"
],
