const workbooks = {
  "Libro 1": [
    "1. Habilidades del Putt (Anotar número de putts metidos)",
    "10 putts caída der→izq 3 pies",
    "10 putts caída izq→der 3 pies",
    "10 putts rectos 3 pies",
    "",
    "10 putts caída der→izq 6 pies",
    "10 putts caída izq→der 6 pies",
    "10 putts rectos 6 pies",
    "",
    "10 putts caída der→izq 9 pies",
    "10 putts caída izq→der 9 pies",
    "10 putts rectos 9 pies",
    "",
    "10 putts caída der→izq 12 pies",
    "10 putts caída izq→der 12 pies",
    "10 putts rectos 12 pies",
    "",
    "10 putts caída der→izq 15 pies",
    "10 putts caída izq→der 15 pies",
    "10 putts rectos 15 pies",
    "",
    "2. Prueba de Putt de Acercamiento (Anota cuántos quedan a 3 pies del hoyo)",
    "25 putts desde 20 pies",
    "25 putts desde 30 pies",
    "25 putts desde 40 pies",
    "25 putts desde 50 pies",
    "",
    "3. Chipping desde el Fringe (Anota el número de chips a cada distancia)",
    "50 chips a bandera roja (corta), a una distancia de 3 pies",
    "50 chips a bandera amarilla (media), a una distancia de 4 pies",
    "50 chips a bandera azul (larga), a una distancia de 5 pies",
    "",
    "4. Chipping desde el Rough (Anota el número de chips a cada distancia)",
    "50 chips a bandera roja (corta), a una distancia de 3 pies",
    "50 chips a bandera amarilla (media), a una distancia de 4 pies",
    "50 chips a bandera azul (larga), a una distancia de 5 pies"
  ],

  "Libro 2": [
    "1. Pitching (En cuántos tiros lograste hacerlo)",
    "20 yardas pitch - Distancia promedio desde el hoyo (10 tiros)",
    "40 yardas pitch - Distancia promedio desde el hoyo (10 tiros)",
    "60 yardas pitch - Distancia promedio desde el hoyo (10 tiros)",
    "80 yardas pitch - Número de bolas en el green de 10 bolas",
    "80 yardas pitch - Distancia promedio desde el hoyo",
    "100 yardas pitch - Número de bolas en el green de 10 bolas",
    "100 yardas pitch - Distancia promedio desde el hoyo",
    "",
    "2. Hierros (En cuántos tiros lograste hacerlo)",
    "Cuenta el número de bolas rectas a la bandera de 100 yardas",
    "Cuenta el número de bolas a la izquierda a la bandera de 100 yardas",
    "Cuenta el número de bolas a la derecha a la bandera de 100 yardas",
    "",
    "Cuenta el número de bolas rectas a la bandera de 125 yardas",
    "Cuenta el número de bolas a la izquierda a la bandera de 125 yardas",
    "Cuenta el número de bolas a la derecha a la bandera de 125 yardas",
    "",
    "Cuenta el número de bolas rectas a la bandera de 150 yardas",
    "Cuenta el número de bolas a la izquierda a la bandera de 150 yardas",
    "Cuenta el número de bolas a la derecha a la bandera de 150 yardas",
    "",
    "Cuenta el número de bolas rectas a la bandera de 175 yardas",
    "Cuenta el número de bolas a la izquierda a la bandera de 175 yardas",
    "Cuenta el número de bolas a la derecha a la bandera de 175 yardas",
    "",
    "Cuenta el número de bolas rectas a la bandera de 200 yardas",
    "Cuenta el número de bolas a la izquierda a la bandera de 200 yardas",
    "Cuenta el número de bolas a la derecha a la bandera de 200 yardas",
    "",
    "3. Driver",
    "Número de bolas que cayeron dentro de un área de 30 yds del objetivo"
  ]
};
